#pragma once

#include <stdint.h>

enum class KeyCode : uint32_t {
	ALT = 18,
	DOWN = 40,
	LEFT = 37,
	RIGHT = 39,
	UP = 38,
	BACKSPACE = 8,
	CAPS_LOCK = 20,
	CTRL = 17,
	DEL = 46,
	END = 35,
	ENTER = 13,
	ESC = 27,
	F1 = 112,
	F2 = 113,
	F3 = 114,
	F4 = 115,
	F5 = 116,
	F6 = 117,
	F7 = 118,
	F8 = 119,
	F9 = 120,
	F10 = 121,
	F11 = 122,
	F12 = 123,
	HOME = 36,
	INSERT = 45,
	NUM_LOCK = 144,
	NUMPAD_0 = 96,
	NUMPAD_1 = 97,
	NUMPAD_2 = 98,
	NUMPAD_3 = 99,
	NUMPAD_4 = 100,
	NUMPAD_5 = 101,
	NUMPAD_6 = 102,
	NUMPAD_7 = 103,
	NUMPAD_8 = 104,
	NUMPAD_9 = 105,
	NUMPAD_MINUS = 109,
	NUMPAD_ASTERIKS = 106,
	NUMPAD_DOT = 110,
	NUMPAD_SLASH = 111,
	NUMPAD_SUM = 107,
	PAGE_DOWN = 34,
	PAGE_UP = 33,
	PAUSE = 19,
	PRINT_SCREEN = 44,
	SCROLL_LOCK = 145,
	SHIFT = 16,
	SPACE = 32,
	TAB = 9,
	A = 65,
	B = 66,
	C = 67,
	D = 68,
	E = 69,
	F = 70,
	G = 71,
	H = 72,
	I = 73,
	J = 74,
	K = 75,
	L = 76,
	M = 77,
	N = 78,
	O = 79,
	P = 80,
	Q = 81,
	R = 82,
	S = 83,
	T = 84,
	U = 85,
	V = 86,
	W = 87,
	X = 88,
	Y = 89,
	Z = 90,
	NUM_0 = 48,
	NUM_1 = 49,
	NUM_2 = 50,
	NUM_3 = 51,
	NUM_4 = 52,
	NUM_5 = 53,
	NUM_6 = 54,
	NUM_7 = 55,
	NUM_8 = 56,
	NUM_9 = 57,
	QUOTE = 192,
	MINUS = 189,
	COMMA = 188,
	SLASH = 191,
	SEMICOLON = 186,
	LEFT_SQRBRACKET = 219,
	RIGHT_SQRBRACKET = 221,
	BACKSLASH = 220,
	EQUALS = 187
};

enum class MouseButton {
	MOUSE_BUTTON_LEFT = 0,
	MOUSE_BUTTON_MIDDLE = 1,
	MOUSE_BUTTON_RIGHT = 2
};

namespace input
{
	void pollEvents();
	float mouseX();
	float mouseY();
	float mouseWheelX();
	float mouseWheelY();
	bool mouseDown(MouseButton button);
	bool mouseClick(MouseButton button);
	bool keyDown(KeyCode keyCode);
	bool keyClick(KeyCode keyCode);
	char getLastChar();
	bool shouldQuit();
	void triggerExit();
	void setLastChar(char v);

	template<typename TFunc, typename TCheck>
	void forEachKeyCode(TFunc func, TCheck check) {
		static KeyCode keyCodes[] = {
			KeyCode::ALT,
			KeyCode::DOWN,
			KeyCode::LEFT,
			KeyCode::RIGHT,
			KeyCode::UP,
			KeyCode::BACKSPACE,
			KeyCode::CAPS_LOCK,
			KeyCode::CTRL,
			KeyCode::DEL,
			KeyCode::END,
			KeyCode::ENTER,
			KeyCode::ESC,
			KeyCode::F1,
			KeyCode::F2,
			KeyCode::F3,
			KeyCode::F4,
			KeyCode::F5,
			KeyCode::F6,
			KeyCode::F7,
			KeyCode::F8,
			KeyCode::F9,
			KeyCode::F10,
			KeyCode::F11,
			KeyCode::F12,
			KeyCode::HOME,
			KeyCode::INSERT,
			KeyCode::NUM_LOCK,
			KeyCode::NUMPAD_0,
			KeyCode::NUMPAD_1,
			KeyCode::NUMPAD_2,
			KeyCode::NUMPAD_3,
			KeyCode::NUMPAD_4,
			KeyCode::NUMPAD_5,
			KeyCode::NUMPAD_6,
			KeyCode::NUMPAD_7,
			KeyCode::NUMPAD_8,
			KeyCode::NUMPAD_9,
			KeyCode::NUMPAD_MINUS,
			KeyCode::NUMPAD_ASTERIKS,
			KeyCode::NUMPAD_DOT,
			KeyCode::NUMPAD_SLASH,
			KeyCode::NUMPAD_SUM,
			KeyCode::PAGE_DOWN,
			KeyCode::PAGE_UP,
			KeyCode::PAUSE,
			KeyCode::PRINT_SCREEN,
			KeyCode::SCROLL_LOCK,
			KeyCode::SHIFT,
			KeyCode::SPACE,
			KeyCode::TAB,
			KeyCode::A,
			KeyCode::B,
			KeyCode::C,
			KeyCode::D,
			KeyCode::E,
			KeyCode::F,
			KeyCode::G,
			KeyCode::H,
			KeyCode::I,
			KeyCode::J,
			KeyCode::K,
			KeyCode::L,
			KeyCode::M,
			KeyCode::N,
			KeyCode::O,
			KeyCode::P,
			KeyCode::Q,
			KeyCode::R,
			KeyCode::S,
			KeyCode::T,
			KeyCode::U,
			KeyCode::V,
			KeyCode::W,
			KeyCode::X,
			KeyCode::Y,
			KeyCode::Z,
			KeyCode::NUM_0,
			KeyCode::NUM_1,
			KeyCode::NUM_2,
			KeyCode::NUM_3,
			KeyCode::NUM_4,
			KeyCode::NUM_5,
			KeyCode::NUM_6,
			KeyCode::NUM_7,
			KeyCode::NUM_8,
			KeyCode::NUM_9,
			KeyCode::QUOTE,
			KeyCode::MINUS,
			KeyCode::COMMA,
			KeyCode::SLASH,
			KeyCode::SEMICOLON,
			KeyCode::LEFT_SQRBRACKET,
			KeyCode::RIGHT_SQRBRACKET,
			KeyCode::BACKSLASH,
			KeyCode::EQUALS
		};
		for (size_t index = 0; index < sizeof(keyCodes) / sizeof(KeyCode); ++index) {
			func(keyCodes[index], check(keyCodes[index]));
		}
	}

	template<typename TFunc>
	static void forEachKeyDown(TFunc func) {
		forEachKeyCode(func, input::keyDown);
	}
}
